apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-service
spec:
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort